[READY TO MERGE] Bandits Steal the Show: Class Selection for the Bandit Antag.
GeneralPantsuIsBadAtCoding/Azure-Peak pull request #352
Opened 2024-09-20 18:09 UTC by Plum-but-gayer

## About The Pull Request
Provides class selection for bandits, giving them six(!!) new classes to choose from, some with subclasses or weapon selection.
Bandits are balanced to now be similar in power level to an adventurer. Looking at the code, they were originally balanced to be in groups of 16 or more. 

Also gives a small update to the bandit camp, adding a few items (spare vulf caps, a healing potion, spare keys, disguise cloaks in a variety of colors so they're not immediately found out) a building (for private RP scenes) and also attempts to remap the forest to make it a little more interesting than the click-drag blocks of duplicate evil tree . jpg. Inspired by some other person's bandit camp revamp PR that I saw once but couldn't find again so I just kinda tried to do it from memory. Shout out to them.

Additionally, bandits now become a latejoinable job role when it's a proper bandit round - if the server rolls for bandits and none are chosen roundstart, players can join later through the latejoin menu. Latejoin slots are capped at what the bandit cap normally is. Bandit migrant waves also still exist and functional normally. 

This is one of my bigger PRs I've done before so there is a possibility of some minor bugs here and there, but I've done my best to test it. Thanks a bunch to Sigma, without them and their support this PR wouldn't be possible. 

### Classes:
_it takes forever to test this and i have no good debug tools so no i didnt take a picture of each class. Sorry!!!_
**Brigand** - axe or club strongman.
![image](https://github.com/user-attachments/assets/7cbb1034-a0ab-4fb6-ad2c-c0a81db7d008)
**Sellsword**- sword mercenary or spear deserter.

**Knave** - sneaky bastard. Comes in no-good thief with lockpicks and poacher with mantraps varieties. 
![image](https://github.com/user-attachments/assets/e4891187-f1a2-43f1-9504-db01d889d778)
**Hedge Knight** - disgraced noble, fallen from grace. Near identical to the black knight errant. 
![image](https://github.com/user-attachments/assets/f9f8045b-eea0-4832-bff3-173b2ebd0293)
~~calls it a draw if you cut off all his limbs~~
**Rogue Mage** - those fools at the academy don't know who they're messing with! Like adventurer mage, but more evil.
![image](https://github.com/user-attachments/assets/8ed93ee9-83d5-42a0-8d0a-88d62999e1be)
**Sawbones** - Have you considered signing up for the bandit medical plan? No, there's no dental. Stop asking. 
![image](https://github.com/user-attachments/assets/21f91ee9-0865-4d6c-8b02-5dd310f71eba)

### Updated Bandit Camp
![image](https://github.com/user-attachments/assets/36579fbc-8e8d-40ba-ac2d-796371b6e623)
![image](https://github.com/user-attachments/assets/34b7657e-ec17-439b-8f94-892f94330c46)

## Why It's Good For The Game

What if our bad guys didn't suck. Better player expression. At the moment bandit 'classes' are chosen by a randomizer - it's hard to roleplay a character when you don't get to select their archetype. This allows antagonist characters to be better fleshed out and have more coherent identities, allowing for a superior roleplay experience. Also will help them not immediately fold over to the first adventurer or guard they encounter. Having them be late joinable also allows people to play dedicated bandit characters, instead of having their normal town role character suddenly be a bandit one day. 

Bandits are historically meant to be a minor antag, but as it says in our code commends a lot of our major antags are disabled as we await custom ones, so bandits are currently fulfilling the role of a major antag with the tools and presence of a minor one. Hopefully these changes allow bandits to be both more meaningful to play as and against.

2024-09-20 18:43 UTC, bearrrrrrrr commented
![images](https://github.com/user-attachments/assets/cb54821a-c8e3-4855-9511-3d2aca064cdf)


"BANDIT steals the show!"

2024-09-22 01:19 UTC, burgerenergy commented on code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
> +	min_pq = 0
I recommend/ask this gets the one and only PQ requirement in the server. Purely because I would want to discourage people from coming in, immediately playing bandit, and either a.) being a menace b.) not knowing where the fuck anything is.

A minimum of one would probably be perfectly fine, as that at least implies they got _**a**_ round in.

2024-09-22 02:06 UTC, Plum-but-gayer commented on code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
> +	min_pq = 0
sounds like an excellent use case for PQ!

2024-09-22 06:58 UTC, bearrrrrrrr commented
not a fan of it being a job for multiple reasons

1. we lack comprehensive job-ban features, out of the gate
2. this means that it can spawn _**regardless**_ of mode; sometimes it is good for us to put on extended instead of roguemode
3. static hostile spawns do not work. see hearth's vikings on implementation. it's literally the same round every round
4. biggest reason, _**as an admin, frankly, i do not trust our playerbase at present to handle this responsibly.**_ i'd like to give it a while for us to weed out the biggest problem players to avoid a headache.

2024-09-22 07:39 UTC, bearrrrrrrr commented
putting this here and in discord; peep code\modules\antagonists\roguetown\villain\vampirelord.dm to see how it does after-spawn class select

2024-09-23 02:27 UTC, crunchypretzels requested changes
hello coder. i need 400 lines of extra code pleab. glory to gitub

2024-09-23 02:27 UTC, crunchypretzels commented on code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
> +
may i suggest for the melee classes

cmode_music = 'sound/music/combat_bandit.ogg'

2024-09-23 02:27 UTC, crunchypretzels commented on code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
> +
and for the ranged...

cmode_music = 'sound/music/combat_bandit2.ogg'

2024-09-23 15:32 UTC, Plum-but-gayer commented on code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
> +
bandit2 my beloved

2024-09-23 15:35 UTC, Plum-but-gayer commented on code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
> +
yes but can I ask your thoughts on this:
https://m.youtube.com/watch?v=hp5jtmpsCKM&pp=ygUWZmxhayB0aGVtZSBkdWFsIHN0cmlrZQ%3D%3D

2024-09-23 17:17 UTC, crunchypretzels commented on code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
> +
while a cool track it doesn't compare to the waltzing melody of Deus Ex - Battery Park (Combat). the building tempo as it grows more frenetic, the marching beat, the ebb and flow of the horns and brass...

2024-09-24 04:16 UTC, coffeecoffeecoffee commented
> not a fan of it being a job for multiple reasons
> 
>     1. we lack comprehensive job-ban features, out of the gate
> 
>     2. this means that it can spawn _**regardless**_ of mode; sometimes it is good for us to put on extended instead of roguemode
> 
>     3. static hostile spawns do not work. see hearth's vikings on implementation. it's literally the same round every round
> 
>     4. biggest reason, _**as an admin, frankly, i do not trust our playerbase at present to handle this responsibly.**_ i'd like to give it a while for us to weed out the biggest problem players to avoid a headache. it is very easy to say 'simply ban them', but understand that literally every single ban or note comes with about 30 minutes of review and log-diving and pm'ing folk, potentially far more
> 
> 
> (otherwise, no objections/notes)

1) i'm pretty sure we just need to port it from ratwood; somebody correct me if I'm wrong but they implemented this, and we can see about porting it very easily if so
2) almost every round is basically extended. i, both as a player and admin, am really tired of it. it makes the game lifeless and the struggle feel pointless. we need more antagonists badly.
3) this may be true; i do feel like there's something to the notion that being able to play an antagonist "character" consistently every round all round has turned out unhealthy in the past, and perhaps we could solve this by having this BE a gamemodespawn that opens up a bunch of bandit "slots" for latejoining rather than being consistently constantly available.
4) we have weeded out LOTS of major problem players, particularly bandit ones, if you recall. this is something we should be doing anyways regardless, and the fact is, right now, we are resting on our laurels and getting used to a lifeless, pointless existence languishing in town every round - and cool things will "wait on us to do X" forever. weeding out problem players is not an achievable goal, it is a constant cleaning task.

2024-09-24 13:23 UTC, bearrrrrrrr commented
> > not a fan of it being a job for multiple reasons
> > ```
> > 1. we lack comprehensive job-ban features, out of the gate
> > 
> > 2. this means that it can spawn _**regardless**_ of mode; sometimes it is good for us to put on extended instead of roguemode
> > 
> > 3. static hostile spawns do not work. see hearth's vikings on implementation. it's literally the same round every round
> > 
> > 4. biggest reason, _**as an admin, frankly, i do not trust our playerbase at present to handle this responsibly.**_ i'd like to give it a while for us to weed out the biggest problem players to avoid a headache. it is very easy to say 'simply ban them', but understand that literally every single ban or note comes with about 30 minutes of review and log-diving and pm'ing folk, potentially far more
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (otherwise, no objections/notes)
> 
>     1. i'm pretty sure we just need to port it from ratwood; somebody correct me if I'm wrong but they implemented this, and we can see about porting it very easily if so
> 
>     2. almost every round is basically extended. i, both as a player and admin, am really tired of it. it makes the game lifeless and the struggle feel pointless. we need more antagonists badly.
> 
>     3. this may be true; i do feel like there's something to the notion that being able to play an antagonist "character" consistently every round all round has turned out unhealthy in the past, and perhaps we could solve this by having this BE a gamemodespawn that opens up a bunch of bandit "slots" for latejoining rather than being consistently constantly available.
> 
>     4. we have weeded out LOTS of major problem players, particularly bandit ones, if you recall. this is something we should be doing anyways regardless, and the fact is, right now, we are resting on our laurels and getting used to a lifeless, pointless existence languishing in town every round - and cool things will "wait on us to do X" forever. weeding out problem players is not an achievable goal, it is a constant cleaning task.

'Almost every round is basically extended'? We have so many antags, some days. People aren't literally constantly in combat, sure, but they're not _constantly safe_ and bored. We have complaints that there's **too much going on** some rounds as-is.

Introducing FO13-style outlaws is not the play. Maybe we make bandit migrant waves more common? Or, honestly, WL'ing people for a bandit role would also be fine tbh. I 100% do not think it is a good idea to say 'yes you can drop in as an antag literally whenever you want' to everybody.

2024-09-24 13:30 UTC, EvenInDeathIStillServe commented
Definitely possible to make the gamemode open up bandit slots in addition to assigning people as bandits roundstart.

2024-09-24 15:53 UTC, AdamElTablawy commented
> > > not a fan of it being a job for multiple reasons
> > > ```
> > > 1. we lack comprehensive job-ban features, out of the gate
> > > 
> > > 2. this means that it can spawn _**regardless**_ of mode; sometimes it is good for us to put on extended instead of roguemode
> > > 
> > > 3. static hostile spawns do not work. see hearth's vikings on implementation. it's literally the same round every round
> > > 
> > > 4. biggest reason, _**as an admin, frankly, i do not trust our playerbase at present to handle this responsibly.**_ i'd like to give it a while for us to weed out the biggest problem players to avoid a headache. it is very easy to say 'simply ban them', but understand that literally every single ban or note comes with about 30 minutes of review and log-diving and pm'ing folk, potentially far more
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > (otherwise, no objections/notes)
> > 
> > 
> > ```
> > 1. i'm pretty sure we just need to port it from ratwood; somebody correct me if I'm wrong but they implemented this, and we can see about porting it very easily if so
> > 
> > 2. almost every round is basically extended. i, both as a player and admin, am really tired of it. it makes the game lifeless and the struggle feel pointless. we need more antagonists badly.
> > 
> > 3. this may be true; i do feel like there's something to the notion that being able to play an antagonist "character" consistently every round all round has turned out unhealthy in the past, and perhaps we could solve this by having this BE a gamemodespawn that opens up a bunch of bandit "slots" for latejoining rather than being consistently constantly available.
> > 
> > 4. we have weeded out LOTS of major problem players, particularly bandit ones, if you recall. this is something we should be doing anyways regardless, and the fact is, right now, we are resting on our laurels and getting used to a lifeless, pointless existence languishing in town every round - and cool things will "wait on us to do X" forever. weeding out problem players is not an achievable goal, it is a constant cleaning task.
> > ```
> 
> 'Almost every round is basically extended'? We have so many antags, some days. People aren't literally constantly in combat, sure. That's not extended. There is so much happening. We have complaints that there's **too much going on** some rounds as-is. It may be worth looking at how antags spawn, but, that being said-
> 
> Introducing FO13-style outlaws is not the play. Maybe we make bandit migrant waves more common? Or, honestly, WL'ing people for a bandit role would also be fine tbh. I 100% do not think it is a good idea to say 'yes you can drop in as an antag literally whenever you want' to everybody.

Difference of opinion, honestly. Most of my friends complain there's not really a lot going on. You'll typically get one antag per round, or two, and they get dumpstered fast. A lot of rounds really aren't that chaotic. (If I was being uncharitable, i'd say that a lot of the people saying there's 'too much' come from Hearthstone or Nova and are accustomed to literally nothing ever.)

All the same, there's no harm in testmerging this for a week or so and seeing how it goes.

2024-09-24 17:06 UTC, chemistrymain3 commented
> 'Almost every round is basically extended'? We have so many antags, some days. People aren't literally constantly in combat, sure. That's not extended. There is so much happening. We have complaints that there's too much going on some rounds as-is. It may be worth looking at how antags spawn, but, that being said-

Difference of opinion, honestly. Most of my friends complain there's not really a lot going on. You'll typically get one antag per round, or two, and they get dumpstered fast. A lot of rounds really aren't that chaotic. (If I was being uncharitable, i'd say that a lot of the people saying there's 'too much' come from Hearthstone or Nova and are accustomed to literally nothing ever.)

All the same, there's no harm in testmerging this for a week or so and seeing how it goes.

2024-09-26 05:37 UTC, chemistrymain3 commented
> > Difference of opinion, honestly. Most of my friends complain there's not really a lot going on. You'll typically get one antag per round, or two, and they get dumpstered fast. A lot of rounds really aren't that chaotic. (If I was being uncharitable, i'd say that a lot of the people saying there's 'too much' come from Hearthstone or Nova and are accustomed to literally nothing ever.)
> > All the same, there's no harm in testmerging this for a week or so and seeing how it goes.
> 
> I mean, this is also a case of 'nobody rolls antags' some rounds, tbf. Yesterday and the day before I did a fun little experiment where I announced really loudly that antags were on and to pretty please enable them in people's prefs.
> 
> We got zero antag rollers.
> 
> This rots.
> 
> I really like the idea of a latejoin being opened up when bandits roll, though. That's dope :3

A big reason nobody rolls antags is that rolling antag means that you are one guy against the town's armada in full plate.

Being able to join as a bandit with a couple other bandits reliably would help resolve this.

2024-10-02 19:38 UTC, bearrrrrrrr commented
just to confirm, as with the PR desc, this is a job that opens up after bandits roll for the round? if so that's awesome, great work :3

2024-10-03 15:35 UTC, merged